### ISSUE TITLE
Remove "version" and "date" from script

### ISSUE THREAD

**Issue by birgersp** [reneboer/python-carnet-client#12]
Version and date written explicitly in the script is unnecessary. This is why you use git.

Comments about who did what in the script are also unnecessary, but less annoying since you don't have to keep updating the text as the code evolves.

I propose that the "version" and "date" lines in the script are removed.

**Comment by reneboer** [comment]
I disagree. I always wonder what version I have if it is not in the script. I do not run it in git I have to download it.
