### ISSUE TITLE
Change "climat" to "climate"

### ISSUE THREAD

**Issue by birgersp** [reneboer/python-carnet-client#13]
Functions regarding climate have a typo

**Comment by reneboer** [comment]
The reason is that the WE Connect API calls it that.

**Comment by birgersp** [comment]
Can you please show where?

**Comment by reneboer** [comment]
Now I look back it is probably because how things where called in one of the app based versions of the carnet version. See wes repo I link to. As people are now using as command I can add it as synonym.
