### ISSUE TITLE
Select Car

### ISSUE THREAD

**Issue by JimKnopf1503** [reneboer/python-carnet-client#19]
Hello Folks!

Thanks for your work so far. I am now facing the "problem" that my account has two active cars and the second one is the e-Golf which is my target.
I can't access the eManager using this script. Reason: the first car (Touran) is selectes as the acitve one in the session "garage". The request of "eManager details" does not contain the vin in it to select the eGolf.
Is there a way, to select the eGolf as the active car for the session, may be by the vin?
If not, it is no problem.
The workaorund would be, to create a new account with only the eGolf registered.

Thanks for answers,
Burkhard

**Comment by reneboer** [comment]
Hi @JimKnopf1503, I have this on my to-do list. Give me a week or two and I'll ask you to test.

**Comment by reneboer** [comment]
Hi @JimKnopf1503 

Can you try the new script in the development branch? To support additional command line options like the vin, the script arguments have changed:

```
pi@raspberry:~ $ python3 we_connect_client.py -h
usage: we_connect_client.py [-h] -u USER -p PASSWORD [-v VIN]
                            [-c {startCharge,stopCharge,getCharge,startClimate,stopClimate,getClimate,startWindowMelt,stopWindowMelt,getWindowMelt,getVIN,remoteLock,remoteUnlock}]
                            [-s SPIN] [-i {0,1,2,3,4,5,6,7,8}] [-d]

 Control your Connected VW.

optional arguments:
  -h, --help            show this help message and exit
  -u USER, --user USER  Your WE-Connect user id.
  -p PASSWORD, --password PASSWORD
                        Your WE-Connect password.
  -v VIN, --vin VIN     Your car VIN if more cars on account.
  -c {startCharge,stopCharge,getCharge,startClimate,stopClimate,getClimate,startWindowMelt,stopWindowMelt,getWindowMelt,getVIN,remoteLock,remoteUnlock}, --command {startCharge,stopCharge,getCharge,startClimate,stopClimate,getClimate,startWindowMelt,stopWindowMelt,getWindowMelt,getVIN,remoteLock,remoteUnlock}
                        Command to send.
  -s SPIN, --spin SPIN  Your WE-Connect s-pin needed for some commands.
  -i {0,1,2,3,4,5,6,7,8}, --index {0,1,2,3,4,5,6,7,8}
                        To get the VIN for the N-th car.
  -d, --debug           Show debug commands.
```

if you could try this to get the VIN of the second car:
```
python we_connect_client.py -u [userID] -p [passwd]  -c getVIN -i 1
```
You should be able to use that VIN value for future requests:
```
python we_connect_client.py -u [userID] -p [passwd]  -v [VIN] -c getCharge
```
and let me know what you get. I do not have more than one car so I had to assume a few things.

**Comment by JimKnopf1503** [comment]
Hi René!

Thank you for your work! I will try it these weekend.
Burkhard

**Comment by JimKnopf1503** [comment]
Hi René!
I tested the script and it worked fine!
Thank you verry much.
In the dark time of the year I will look, if I can make a C++ version of it.

Thanks a lot!
Burkhard

**Comment by reneboer** [comment]
Hi Jim,

Thanks for testing this. I will update the master branch later this week.

Cheers Rene

**Comment by reneboer** [comment]
This now works. Closing issue.
