### ISSUE TITLE
Login not working anymore?

### ISSUE THREAD

**Issue by IPSCoyote** [reneboer/python-carnet-client#20]
Hi,

I use the "vw_carnet_web.py retrieveCarNetInfo" Skript directly and process the data afterwards. 
Since some days the logon seems not to work anymore. At least no data is returned anymore :(

(Why can't VW simply offer a formal data retrieval point ? :( )

**Comment by reneboer** [comment]
Hi,

Please change to the script found in this repository. That works with the latest VW portal.

And totally agree, why not give us a documented API!?!
