### ISSUE TITLE
Add mqtt command for better home automation integration 

### ISSUE THREAD

**Issue by bgewehr** [reneboer/python-carnet-client#23]
In my fork https://github.com/bgewehr/volkswagen-carnet-client I have implemented a new mqtt command to poll carnet data in a cronjob and push it to mosquitto. Are you interested to receive this as a pull request, @reneboer ?

**Comment by reneboer** [comment]
Hi @bgewehr ,
As I am no longer in a position to test this all and have no time either at the moment, feel free to take this to the next level. 
Cheers Rene
