### ISSUE TITLE
A way to login via App method is found under JavaScript for ioBroker: https://github.com/TA2k/ioBroker.vw-weconnect/

### ISSUE THREAD

**Issue by oakedcorn** [reneboer/python-carnet-client#24]
A way to login via App method is found under JavaScript for ioBroker: https://github.com/TA2k/ioBroker.vw-weconnect/
Just for information if you like to switch from Web login. There are plenty of additional information.

_Originally posted by @Sneak-L8 in https://github.com/reneboer/python-carnet-client/issues/5#issuecomment-552559589_

**Comment by oakedcorn** [comment]
It would be super-great if someone could translate this to a python module.

**Comment by reneboer** [comment]
Hi,
Soon I will no longer have a VW to develop and test all this against. But anyone feel free to take the code and run with it as I have done with the foundations created by others.
