### ISSUE TITLE
SSLError raised recently

### ISSUE THREAD

**Issue by Sh0n** [reneboer/python-carnet-client#25]
Hi, 

Recently, i get new error when i try to use this script (it works last week !) : 

```
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.portal.volkswagen-we.com', port=443): Max retries exceeded with url: /portal/en_GB/web/guest/home (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
```

Any idea ?

**Comment by odelma** [comment]
Same here 🙋‍♂️

**Comment by reneboer** [comment]
I posted an update that skips the certificate check. For me it works again.

**Comment by odelma** [comment]
Thanks, looks like it is working again :smile: Do you know if there is any way to disable these warnings:
`/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,`

edit: this did the trick:
`from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)`
https://stackoverflow.com/questions/27981545/suppress-insecurerequestwarning-unverified-https-request-is-being-made-in-pytho

**Comment by reneboer** [comment]
The real problem is a incomplete certificate chain at the VW site side, so other than your trick I would not know.

**Comment by Sh0n** [comment]
Thanks a lot ! it works perfectly !
