### ISSUE TITLE
I'm getting "Failed to login Failed to post portlet page" with latest version

### ISSUE THREAD

**Issue by bgewehr** [reneboer/python-carnet-client#26]
Hi, after a longer time where everything went well, I tried this new version and get the above error on an spin transaction. How can I help tracing?

**Comment by bgewehr** [comment]
I tried again and again and received a different result sometimes:

```
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
=== login complete ===
/-/mainnavigation/get-fully-loaded-cars
/-/mainnavigation/load-car-details/WVWZZZ3HZJXXXXXXX
Check security level for: P_QSACT
/-/rah/quick-start
{"errorHeaderCopybookId":"vw-mod-carnet-d5-service-rah-headline-notification-quickstarttechnical-error","errorCode":"2","errorTextCopybookId":"vw-mod-carnet-d5-service-rah-text-notification-quickstarttechnical-error"}
/-/logout/revoke
```

**Comment by reneboer** [comment]
Sorry, I do not have the possibility to test. Is this all working via the normal portal?

I know VW made some change causing a SSL certificate issue that is why the new version is posted that skips the SSL certificate validation. No idea if this is related or not.

**Comment by bgewehr** [comment]
Yes, from the official portal all is working fine.

Will check the code for more certificate-based issues...

**Comment by bgewehr** [comment]
I now disabled cert verification on all requests in the script. Works again.

**Comment by reneboer** [comment]
Well done. I merged your updates in. Thanks.
