### ISSUE TITLE
InsecureRequestWarning

### ISSUE THREAD

**Issue by addellll** [reneboer/python-carnet-client#29]
`InsecureRequestWarning,
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`

I know this git is not supported more, but for me i get alot of InsecureRequestWarning. My solution to this is: 
```
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```
How ever if this is a good idea or not i cant tell since i am no python coder.

**Comment by reneboer** [comment]
Hi @addellll I have added the code in the latest version. Only in debug mode the warning will still be displayed.
