### ISSUE TITLE
Code ist great and working. Can someone translate it to C++?

### ISSUE THREAD

**Issue by JimKnopf1503** [reneboer/python-carnet-client#3]
Hello!

Thank you for this great code! I am not able to write python code and want to use this in a c++ project.
Can someone translate it to C++?
I can't even get the # Request landing page and get CSFR:  part working in C++.

Thank your for any help.
Burkhard Venus

**Comment by reneboer** [comment]
Sorry, I cannot. But anyone feel free to help.

**Comment by birgersp** [comment]
Which OS? Windows?

**Comment by JimKnopf1503** [comment]
Hello!
I have written the C++ code for Linux, which was working til We-Connect came up.
I am now trying to get what has changed.

Burkhard

**Comment by reneboer** [comment]
@JimKnopf1503 if you have a repo I can link to for you C++ version, let me know and I can include it in the readme. For now I'll close this issue as it is not related to the python version.

**Comment by JimKnopf1503** [comment]
Thanks Rene!
But the C++ version dont work anymore couse of the WeConnect change.
The App Version seems much more complex. Scrambling wit different keys (code challange).
I stopped working on it, it is too high for me.
Burkhard

**Comment by birgersp** [comment]
Jim,

I'm working on a kotlin port myself (also broken by the change), which I think will be working again with just a couple more hours of coding. The code here is very much cleaned up in terms of readability now. If there are any parts of the code where the steps are unclear, you can probably just create an issue about it and someone will improve it even more :)

**Comment by JimKnopf1503** [comment]
Thanks for that hint, but I am using the app protocol, not the one of the web portal.
That seems much more different.
