### ISSUE TITLE
Help to get it work in c++

### ISSUE THREAD

**Issue by JimKnopf1503** [reneboer/python-carnet-client#31]
Hi Everybody!
Sorry, that I post here, there is nothing wrong with the script.
I am converting it to work in C++ with libcurl, but i stuck in Step 5 of login procedure.
I allways get a bad request response.
Below detailed infos.
Does anyone see what went wrong?

Thanks,
Burkhard

URL:
https://identity.vwgroup.io//signin-service/v1/b7a5bb47-f875-47cf-ab83-2ba3bf6bb738@apps_vw-dilab_com/login/identifier
Postfields: email=notmyreal@host.de&relayState=9f098e5f5a20a5efc218b97f4b87667e21492b0b&hmac=bfe175979aeb2eb47c82e80a37693eca71f834dcd798f54c567f651d8549c86b&_csrf=237c3c0f-6f01-4f09-9f6a-2a3530ceb75a
Headers: (rportet by curl debug)
Host: identity.vwgroup.io
0085: Cookie: SESSION=MjdmMDM2NWQtNmMxYS00MWE2LWIxODgtZmJhMWZiMmQ4MjEw
00c5: ; vcap_journey=6ffe6716-07cf-4a33-9cfa-e18d21283b7a
00fa: Accept-Encoding: gzip, deflate, br
011e: Accept-Language: en-US,nl;q=0.7,en;q=0.3
0148: Accept: 'text/html,application/xhtml+xml,application/xml,applica
0188: tion/json;q=0.9,*/*;q=0.8
01a3: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) G
01e3: ecko/20100101 Firefox/68.0
01ff: Connection: keep-alive
0217: Pragma: no-cache
0229: Cache-Control: no-cache
0242: Content-Type: application/x-www-form-urlencoded
0273: Referer:  https://identity.vwgroup.io/signin-service/v1/signin/b
02b3: 7a5bb47-f875-47cf-ab83-2ba3bf6bb738@apps_vw-dilab_com?relayState
02f3: =9f098e5f5a20a5efc218b97f4b87667e21492b0b

Responseheader:
HTTP/1.1 400 Bad Request
Date: Mon, 20 Jan 2020 12:58:29 GMT
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Language: en
Expires: 0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: 0bd75c0e-30e1-468c-5ca4-41acb93a96bf
X-Xss-Protection: 1; mode=block

**Comment by reneboer** [comment]
Hi Jim,

I know I could not get it working unless the SSL library supports SNI. Not sure if that is your problem, but would be worth checking.

**Comment by JimKnopf1503** [comment]
Hi Rene!
Thanks for the hint.
I will use wireshark so see whats the difference.
Burkhard

**Comment by JimKnopf1503** [comment]
Hi!

Edit: I found my bad mistake! I was still using the url from step4, shame on me.
Burkhard

**Comment by JimKnopf1503** [comment]
Hi!
It is all working now.
Thanks! Closed.
Burkhard
