### ISSUE TITLE
Featur Request: Getting battery State Of Charge (SoC) for eGolf and other EVs

### ISSUE THREAD

**Issue by chrm-software** [reneboer/python-carnet-client#35]
Hi, on the WeConnect portal there are two information about the battery of the EV: estimated range mileage and the state of charge (SoC, usually in %).

While the range is a number and already available in your carnet client, the SoC only appears as a picture, see screenshot:
https://chrm.info/tmp/we_portal_egolf.png

The picture is an embedded svg graphics (CSS class "ct-chart-donut") which visualize the SoC in 10% chunks.

Is it possible to parse the svg data and make the SoC available?
How can I provide more info for this function?

Thank you for your good work!

**Comment by IPSCoyote** [comment]
I'm not on the latest build on this and use the photon script to get the data for further processing in a smartphone system. The JSON Data does contain the SoC in the "eManager" part.

**Comment by chrm-software** [comment]
Oh, sorry! Of course, its already there in emanager...
My fault. Please, close this.
