### ISSUE TITLE
WeConnect ID support?

### ISSUE THREAD

**Issue by andig** [reneboer/python-carnet-client#37]
Recent VW ID cars like ID.3 do no longer see to appear in the „old“ carnet portal (or do so by chance). Further, the new WeConnect ID app provides more precise battery soc values than the old portal which had only 10% steps. 

Would appreciate any feedback on details of the login/api flow for the newer weconnect id app.

**Comment by reneboer** [comment]
Hi,
I do not have a VW car anymore, so I cannot maintain these scripts anymore. Sorry.
