### ISSUE TITLE
Changes to Portal

### ISSUE THREAD

**Issue by thomaskien** [reneboer/python-carnet-client#38]
Hi!
Are there any news about the changes of today "Das We Connect Portal verabschiedet sich am 27.04.2021", it looks like that broke all my scripts using this great project here - is there a way to revive it?
Regards,
Thomas

**Comment by IPSCoyote** [comment]
Same here :(

**Comment by JimKnopf1503** [comment]
This way is over. Actual the only way would by to emulate the original VW App WeConnect or WeConnectID and use these protocols. They are much harder to analyse and backengeneer.

**Comment by IPSCoyote** [comment]
There's only one useful way: Send Mails to VW and request an official API like e.g. BMW ConnectDrive has. 
"Hacking" Portals is not the way IoT should be done in 2021....

**Comment by JimKnopf1503** [comment]
You are absolutly right! I have already wrote a Email this morning directly to **herbert.diess@volkswagen.de**, requesting support to get an API.

**Comment by BerndGewehr** [comment]
Try the we connect adapter from iobroker instead. That one still works today on a Skoda and a VW of mine.

**Comment by thomaskien** [comment]
> Try the we connect adapter from iobroker instead. That one still works today on a Skoda and a VW of mine.

@bgewehr does writing values like charging current/climatisation work for you with that or just reading?
for read only I now use evcc as workaround:
`
./evcc vehicle -l trace | grep '{"charger":{"settings":{"maxChargeCurrent":{"conten' > /root/solar/vehicle.json
`
that outputs a json with the most important information like SOC, Current, Cable-Status etc. at least...

**Comment by bgewehr** [comment]
Sorry, since I own a combustion engine model, I can‘t tell. What I can tell is that flash and horn switch etc. can be bound to a mqtt service for reading and writing. Would be glad to hear what you achieved… pls Share.
