### ISSUE TITLE
does not work with "we connect" update

### ISSUE THREAD

**Issue by Mirarkitty** [reneboer/python-carnet-client#5]
Seems like VW decided to update the login part of the services and this no longer works?

**Comment by reneboer** [comment]
Just found that out my self as well. It looks like quite a change and I do not have time the next four weeks to look at this.

**Comment by Mirarkitty** [comment]
I'm not a python person, I did an attempt but all I end up with is a 403 Forbidden page. :/
```
	base = "https://www.portal.volkswagen-we.com/"
        auth_base = "https://identity.vwgroup.io"
...
        hidden__csrf_re = re.compile('<input type="hidden" name="_csrf" value="([^"]*)"/>')
	hidden_relaystatetoken_re = re.compile('<input type="hidden" name="relayStateToken" value="([^"]*)"/>')


	def extract_hidden_relaystatetoken(r):
		return hidden_relaystatetoken_re.search(r.text).group(1)

	def extract_hidden__csrf(r):
		return hidden__csrf_re.search(r.text).group(1)

	# now get actual login page and get session id and ViewState
	r = s.get(ref_url, headers=AUTHHEADERS)
        # print "",r.text
	if r.status_code != 200:
		return ""

        hidden__csrf=extract_hidden__csrf(r);
        hidden_relaystatetoken=extract_hidden_relaystatetoken(r);
        login_url=extract_login_url(r);

        print "csrf",hidden__csrf
        print "rst",hidden_relaystatetoken

	AUTHHEADERS["Referer"] = ref_url
#	AUTHHEADERS["X-CSRF-Token"] = ''
#	AUTHHEADERS["Faces-Request"] = "partial/ajax"
        
	post_data = {
                'email': email,
                'password': password,
                'relayStateToken': hidden_relaystatetoken,
                '_csrf': hidden__csrf,
                'login': 'true',
	}

        print "session 5 - login at ",auth_base+login_url

        AUTHHEADERS["Content-Type"]='application/json'
        
	r = s.post(auth_base + login_url, data=post_data, headers=AUTHHEADERS)

```

**Comment by Mirarkitty** [comment]
Looks like the requests after logging in are very similar. No update in that part of the system.

**Comment by birgersp** [comment]
I'm hoping someone can find out if and how to log in to the service. I'd like to contribute in any way I can, but I'm fumbling in the dark a little. What's the best way to determine what traffic goes between the client and VW servers? Do you have to use Wireshark?

**Comment by Mirarkitty** [comment]
I use firefox, ctrl-shift+k brings up debug opportunities, network tab gives all the headers and talk that's going on.

**Comment by jaybora** [comment]
> Looks like the requests after logging in are very similar. No update in that part of the system.

Mirakitty are you actively working on fixing the login part? More if I should give it a go. I'm not a python man but have done a couple of screen scraping apps before in java and golang.
And I need it to work for my e-golf integration into my domoticz home automation setup.

**Comment by birgersp** [comment]
All hands on deck! Anyone capable and willing should give it a go, imo ;)

**Comment by jaybora** [comment]
I think I am halfway through the login procedure. This site has almost 10 pages to go through in order to just login.

**Comment by FritzJo** [comment]
I'am trying to get it working as well, but no real progress on my side.
Its a shame that VW doesn't offer a public API...

**Comment by jaybora** [comment]
#7 Is ready for you service :-) It is working for me now. I can start and stop the charging.

**Comment by birgersp** [comment]
If we have to, I guess another option is to reach out to VW?

**Comment by Mirarkitty** [comment]
No, sorry, been busy.

#7 didn't work for me.

"&#39;ve entered too many wrong email/password combinations. Please wait a moment before you try again."

I get that in this post:
```

	r = s.post(login_action_url, data=post_data, headers=AUTHHEADERS, allow_redirects=False)

	if r.status_code != 302:
		return ""

```
status code is 200 and that's a new login form with that text. I can login fine in the browser.

**Comment by oakedcorn** [comment]
> #7 Is ready for you service :-) It is working for me now. I can start and stop the charging.

Great job, thanks a lot! It works perfectly for me.

I was using [vw_carnet_app.py](https://github.com/wez3/volkswagen-carnet-client/blob/master/vw_carnet_app.py) before, which provided 1% battery SoC accuracy (web api rounds to nearest 10% multiple) and outside temperature data - very useful. Unfortunately this script also got broken with the new login. It would be great if anyone is able to fix that one too.

**Comment by bausi2k** [comment]
Hi,

having an typecast issue? any ideas:
```
Traceback (most recent call last):
  File "vw_carnet_rb1.py", line 206, in <module>
    url = CarNetLogin(s,CARNET_USERNAME,CARNET_PASSWORD)
  File "vw_carnet_rb1.py", line 65, in CarNetLogin
    responseData = json.loads(r.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

br.kg

**Comment by birgersp** [comment]
@Mirarkitty #7 works like a charm for me. Are you absolutely sure there's no error on your end?

**Comment by Mirarkitty** [comment]
I can't be 100% sure, but it doesn't let me log in anyway. I only changed uid and password. I'm not sure why the script gives the error but not the website.

**Comment by Mirarkitty** [comment]
And yes, running with python 3 gives that type error.

**Comment by jaybora** [comment]
@bausi2k It is related to you python version. You can use python 3.7 or wait until I fix next week.

**Comment by Mirarkitty** [comment]
Or do this change:
	#login_url = json.loads(r.content).get("loginURL").get("path")
	login_url = r.json().get("loginURL").get("path")

**Comment by bausi2k** [comment]
> Or do this change:
> #login_url = json.loads(r.content).get("loginURL").get("path")
> login_url = r.json().get("loginURL").get("path")

worked! thx

**Comment by Mirarkitty** [comment]
Is it just me or did the login change again? I get a two step (email, password) now.

**Comment by youpixel** [comment]
Today I did some changes to the code to match it with the new login screen. Sorry, it is a bit messy... But you get an idea how it could work. 

Pull: https://github.com/reneboer/python-carnet-client/pull/8/commits/65a5381e9081cc6c78a4cf4ab843c5f25aa4c6fb

Raw file: https://github.com/reneboer/python-carnet-client/blob/65a5381e9081cc6c78a4cf4ab843c5f25aa4c6fb/vw_carnet_rb1.py

Cheers

**Comment by jdrescher2006** [comment]
> Today I did some changes to the code to match it with the new login screen. Sorry, it is a bit messy... But you get an idea how it could work.

Thank you very much, it works for me.

**Comment by ottopaulsen** [comment]
Thank you for the great work done here! The latest version (PR#8) works fine for me.

I am trying to make a javascript version of this procedure (node.js), but I ran into a problem.
When posting the login_action_url with email and other data in the body, I get 403 Forbidden, and no further explanation. First I got a message that cookies and javascript must be enabled, but after enabling cookies, I got one step further, now just getting Forbidden.

Have you any ideas for how to get around this?

Otto

**Comment by iemenuyttenhove** [comment]
I made a working C# version for an Azure Function, if anyone is interested I can clean it up and share it 😉

**Comment by JimKnopf1503** [comment]
Latest version dont seem to work for me. Login looks good, but i got no data from the requests.
============= RESTART: D:\Download\CarNetPython\CarNetPython.py =============
/-/msgc/get-new-messages
b'{"messageList":[],"errorCode":"0"}'
/-/vsr/request-vsr
b''
/-/vsr/get-vsr
b''
/-/cf/get-location
b''
/-/vehicle-info/get-vehicle-details
b'{"vehicleDetails":{"lastConnectionTimeStamp":["--","--"],"distanceCovered":"--","range":"","serviceInspectionData":"--","oilInspectionData":"--","showOil":true,"showService":true,"flightMode":false},"errorCode":"0"}'
/-/emanager/get-emanager
b''
>>> 

I've tryed a look at the app protocol using burp but I gave up, it looks verry complexe.

Thanks for help,
Burkhard

**Comment by ottopaulsen** [comment]
> I made a working C# version for an Azure Function, if anyone is interested I can clean it up and share it 😉

Yes, @iemenuyttenhove, I would like to take a look, as I am struggling with my Javascript/node.js version. I have noticed that the CarNet app uses X-XSRF-TOKEN, but it seems to not be used in the Python version, and I cannot figure out where it is coming from. I am getting Forbidden (see above).

Otto

**Comment by 0rsa** [comment]
I have this error with youpixel modification:
Traceback (most recent call last):
  File "/home/flo/carnet/vw_carnet_app.py", line 271, in <module>
    url = CarNetLogin(s,CARNET_USERNAME,CARNET_PASSWORD)
  File "/home/flo/carnet/vw_carnet_app.py", line 170, in CarNetLogin
    portlet_code = extract_code(r.url)
  File "/home/flo/carnet/vw_carnet_app.py", line 80, in extract_code
    return authcode_re.search(r).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

-------------------

FIXED: you need to login at least once to the new desktop portal (to set some preferences at first login) and then it works!
Thanks!

**Comment by birgersp** [comment]
@ottopaulsen

> Thank you for the great work done here! The latest version (PR#8) works fine for me.
> 
> I am trying to make a javascript version of this procedure (node.js), but I ran into a problem.
> When posting the login_action_url with email and other data in the body, I get 403 Forbidden, and no further explanation. First I got a message that cookies and javascript must be enabled, but after enabling cookies, I got one step further, now just getting Forbidden.
> 
> Have you any ideas for how to get around this?
> 
> Otto

> Yes, @iemenuyttenhove, I would like to take a look, as I am struggling with my Javascript/node.js version. I have noticed that the CarNet app uses X-XSRF-TOKEN, but it seems to not be used in the Python version, and I cannot figure out where it is coming from. I am getting Forbidden (see above).
> 
> Otto

I'm having the same issue as you, 403 Forbidden on the POST request (but in a Kotlin app).
I'm going to clean up the python script, to try to pinpoint exactly what it does different compared to my app.
Please let us know if you find out anything.

**Comment by reneboer** [comment]
Hi,

Thanks for all your help on this. I will give it a test run and update the master.

Cheers Rene

**Comment by birgersp** [comment]
@ottopaulsen in an attempt to figure out how to succesfully port the code and get the changes working, I've created my own repo to clean up this code as much as possible. If you're interested: https://github.com/birgersp/carnet-client

**Comment by Mirarkitty** [comment]
I can't login using firefox right now, so I'm not sure what's up.

**Comment by birgersp** [comment]
I can login without problems. Using Chrome, and using the norwegian VW website (if it matters).
Script is also working fine.

**Comment by youpixel** [comment]
> @ottopaulsen in an attempt to figure out how to succesfully port the code and get the changes working, I've created my own repo to clean up this code as much as possible. If you're interested: https://github.com/birgersp/carnet-client

Great! Looks solid and works like a charm

**Comment by FritzJo** [comment]
> @ottopaulsen in an attempt to figure out how to succesfully port the code and get the changes working, I've created my own repo to clean up this code as much as possible. If you're interested: https://github.com/birgersp/carnet-client

works perfectly for my usecase! Thanks. Will you create a pull request?

**Comment by reneboer** [comment]
Hi,

I am working on a new version taking a lot of the changes done by both @ottopaulsen and @birgersp and updating the commands supported as there are some changes.

I will merge all that next week I think.

Cheers.

**Comment by birgersp** [comment]
> works perfectly for my usecase! Thanks. Will you create a pull request?

I would, if I thought it had a chance of being merged ;-)
Also, I'm planning to add my Kotlin code to the same repository, once I get the time for it.

@reneboer Please note you have 3 PRs. And if you're looking for contributions and collaboration, I suggest you consider merging (or rejecting) them. If you change the codebase now without merging, you're just messing up our PRs.

**Comment by Mirarkitty** [comment]
Seems like my ban is over and I can use this (#8) again.

**Comment by reneboer** [comment]
All PRs are now merged. The last one (#8) gave some conflicts so I have too see if it all is working as it should now. New version is coming later.

**Comment by reneboer** [comment]
Hi,
I created a development branch with a new script called we_connect_client.py. 
It does not seem reliable though, but the portal gives me problems right now as well. On the portal I get this after the login instead of the overview page
> System - MBB-AuthorizationServer
> Status - 503 - Service Unavailable

Not sure if it is because of too many logins in a short period or what else. I get the same with the other carnet_client.py script from @birgersp btw.

Please give it a try and let me know your experiance. @Mirarkitty  @birgersp, @ottopaulsen @youpixel

**Comment by birgersp** [comment]
Just gave the script a go, and I didn't have any issues with it

**Comment by reneboer** [comment]
Must have been the portal as the script is working fine for me now too. I made a few more updates and I think it is ready to go out, and close this issue.

**Comment by birgersp** [comment]
I agree, this issue is long gone now ;-)

**Comment by Mirarkitty** [comment]
The portal is up and down a lot. I keep logs... 
This script is working a lot better than their backend XD

**Comment by reneboer** [comment]
Hi, I think the script is stable for the WE Connect portal so I am closing this issue. All of you thanks for your help.

**Comment by Mirarkitty** [comment]
Yes, seems stable now.

**Comment by JimKnopf1503** [comment]
Hi!

I have still problems. Login is working. Get all cars ist working. Car info is working. But: 
get location = errorcode 2
get vehicle details = errorcode 0, but no data
{"vehicleDetails":{"lastConnectionTimeStamp":["--","--"],"distanceCovered":"--","range":"","serviceInspectionData":"--","oilInspectionData":"--","showOil":true,"showService":true,"flightMode":false},"errorCode":"0"}

get emanager:
{"errorCode":"0","EManager":{"rbc":null,"rpc":null,"rdt":null,"actionPending":false,"rdtAvailable":false}}

In my browser all infos are displayed.

This is an eGolf, as the second car, I changed the line "vin= response .....[1]"
Burkhard

**Comment by Mirarkitty** [comment]
That's odd. Location works for me. Make a new ticket though?

**Comment by reneboer** [comment]
Hi, Yes please make a new issue. So we can track under that.
I noticed in the latest responses from the site that the VIN of the car is now part of the URL to use and it as I have only one car I only see that. I am assuming if you just replace that with the VIN of the second car it will work. This will require some changes though. I can make an extra parameter for example.

**Comment by Mirarkitty** [comment]
Did they break it again?

**Comment by birgersp** [comment]
No. What makes you think that they did?

**Comment by Mirarkitty** [comment]
My scripts stopped working. But I'll search locally then.

**Comment by reneboer** [comment]
I am not seeing any problems. Have you logged on to the portal? Subscription expired? Just trowing some things out there.

**Comment by Mirarkitty** [comment]
I had a resolv issue. But now they changed something again. This fixes it; insert .* between novalidate and action:

	login_action_url_re = re.compile('<formclass="content"id="emailPasswordForm"name="emailPasswordForm"method="POST"novalidate.*action="([^"]*)">')

I don't know if this is a good fix. They added =true to novalidate.

**Comment by ottopaulsen** [comment]
Thank you, @Mirarkitty, for the solution. I had just discovered that it was not working, and saw your solution before I got the time to troubleshoot myself.

I have now finished my Javascript version of the script. I am using it in a module for MagicMirror. You can see my solution on [github.com/ottopaulsen/MMM-WeConnect](https://github.com/ottopaulsen/MMM-WeConnect). It is really cool, showing a car-sketch on a screen in my kitchen where I can see whether the car is driving, parked, connected, charging, what the battery capacity is, and so on. I could not have done this without help from this repo, so thank you all!

Otto

**Comment by Mirarkitty** [comment]
I suspect something is changed again, I fail to login but I haven't researched more. I get to 'getloginstatus' but not more.

**Comment by FritzJo** [comment]
I can't replicate the problem right now. Everything seems normal to me.

**Comment by birgersp** [comment]
Are you able to log in to your account on the official app/website? I'm not, which leads me to believe that there is an issue with the service.

**Comment by ottopaulsen** [comment]
It is working fine now, but they have been down a lot lately.

**Comment by Mirarkitty** [comment]
Yes, it seems like it didn't work for the script but it worked on the web when I were testing, so I guess REALLY glitchy. It worked for a few hours today, so I guess the login procedures are still ok.

**Comment by reneboer** [comment]
I posted a support request with VW and they admit they are having issues and are working as hard as they can.. usual bla bla etc...

**Comment by birgersp** [comment]
Thanks for doing that @reneboer. I meant to do it myself, glad to hear it's not just an issue with my account

**Comment by Sneak-L8** [comment]
A way to login via App method is found under JavaScript for ioBroker: https://github.com/TA2k/ioBroker.vw-weconnect/
Just for information if you like to switch from Web login. There are plenty of additional information.
