### ISSUE TITLE
Development should take place in main branch

### ISSUE THREAD

**Issue by birgersp** [reneboer/python-carnet-client#9]
Hi,

I see you've created another branch for development, now with two scripts doing virtually the same thing.
Why is this? If you want to keep a "stable" version of the script, create a tag on a commit where the script was working as intended.

I propose:
- Merge "development" into master,
- remove development,
- remove "vw_carnet_rb1.py"
- commit
- tag with "v1" or something similar

**Comment by reneboer** [comment]
It is a development branch because it is not final. I work on more projects where things are handled like this. You test a development version before you update the master.

**Comment by birgersp** [comment]
Okay. But why do you keep two scripts in the repo? Shouldn't there be just one?
